steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy authenticateBidder \
        --gen2 \
        --runtime=nodejs18 \
        --trigger-http \
        --allow-unauthenticated \
        --source=functions
  dir: 'functions'